language: node_js
sudo: false
node_js:
- '0.12'
- 4.2
- stable
script:
- npm test
after_success:
- npm run coveralls
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_cb4d3d070e32_key -iv $encrypted_cb4d3d070e32_iv -in auth.js.enc -out test/resources/auth.js -d || true'
