################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
contest/E \
contest/D \
contest/C \
contest/B \
contest/A \
Ulticoder \
Topcoder \
. \
Maths/PrimeNumber \
Maths/NumberSystemsOrSequencies/443HumbleNumbers \
Maths/NumberSystemsOrSequencies/10408FareySequences \
Maths/NumberSystemsOrSequencies/10042SmithNumbers \
Maths/Grid/10182BeeMaja \
Maths/616CoconutsRevisited \
Maths/382Perfection \
Maths/264CountOnCantor \
Maths/1225DigitCounting \
Maths/12004BubbleSort \
Maths/11723NumberingRoads \
Maths/11718FantasyOfSummation \
Maths/11254ConsecutiveIntegers \
Maths/11231BlackAndWhitePainting \
Maths/11130BilliardBounces \
Maths/10940ThrowingCardsAwayII \
Maths/10751Chessboard \
Maths/10719QuotientPolynomial \
Maths/10718BitMask \
Maths/10346Peter'sSmokes \
Maths/10233DermubaTriangle \
Maths/10161AntOnAChessBoard \
Graph/TopologicalSort/872Ordering \
Graph/TopologicalSort/11060Beverages \
Graph/TopologicalSort/10305OrderingTasks \
Graph/StronglyConnectedComponents/247CallingCircles \
Graph/StronglyConnectedComponents/11838ComeAndGo \
Graph/StronglyConnectedComponents/11504Dominos \
Graph/SpecialGraphs/10459TheTreeRoot \
Graph/SpecialGraphs/10054TheNecklace \
Graph/SingleSourceShortestPath \
Graph/SingleSourceShortestPath/929NumberMaze \
Graph/SingleSourceShortestPath/924SpreadingTheNews \
Graph/SingleSourceShortestPath/558Wormholes \
Graph/SingleSourceShortestPath/429WordTransformation \
Graph/SingleSourceShortestPath/314Robot \
Graph/SingleSourceShortestPath/12160UnlocktheLock \
Graph/SingleSourceShortestPath/12047HighestPaidToll \
Graph/SingleSourceShortestPath/11492Babel \
Graph/SingleSourceShortestPath/1112MiceAndMaze \
Graph/SingleSourceShortestPath/11101MallMania \
Graph/SingleSourceShortestPath/10986SendingEmails \
Graph/SingleSourceShortestPath/10801LiftHopping \
Graph/SingleSourceShortestPath/10653BombsNOtheyAreMines \
Graph/SingleSourceShortestPath/10449Traffic \
Graph/SingleSourceShortestPath/10278FireStation \
Graph/MinimumSpanningTree \
Graph/MinimumSpanningTree/11747HeavyCycleEdges \
Graph/MinimumSpanningTree/11631DarkRoads \
Graph/MinimumSpanningTree/11228TransportationSystem \
Graph/MinimumSpanningTree/10600ACMContestAndBlackout \
Graph/MinimumSpanningTree/10369ArcticNetwork \
Graph/MinimumSpanningTree/10048Audiophobia \
Graph/MaxFlow \
Graph/MaxFlow/259SoftwareAllocation \
Graph/GraphTraversal/12442ForwardingEmails \
Graph/GraphTraversal/11906KightsInWarGrid \
Graph/GraphTraversal/11831StickerCollectorRobot \
Graph/FloodFillAndFindingConnectedComponents/11953Battleships \
Graph/FloodFillAndFindingConnectedComponents/11094Continents \
Graph/FloodFillAndFindingConnectedComponents/1103AncientMessages \
Graph/BipartiteGraphCheck/11396ClawDecomposition \
Graph/BipartiteGraphCheck/11080PlaceTheGuards \
Graph/BipartiteGraphCheck/10004Bicoloring \
Graph/ArticulationPointsAndBridges/796CriticalLinks \
Graph/ArticulationPointsAndBridges/315Network \
Graph/ArticulationPointsAndBridges/10765DovesAndBombs \
Graph/AllPairsShortestPath/821PageHopping \
Graph/AllPairsShortestPath/334IdentifyingConcurrentEvents \
Graph/AllPairsShortestPath/11463Commandos \
Graph/AllPairsShortestPath/1056DegreesOfSeparation \
Graph/AllPairsShortestPath/104Arbitrage \
Graph/AllPairsShortestPath/10171MeetingProfMiguel \
Graph/11167MonkeysInTheEmeiMountain \
Graph/10746CrimeWave \
Graph/10187FromDuskTillDawn \
Geomatry/Polygon \
Geomatry/Polygon/1111TrashRemoval \
Geomatry/Polygon/10652BoardWrapping \
Geomatry/920SunnyMountains \
Geomatry/11909SoyaMilk \
Geomatry/11665ChineseInk \
Geomatry/11574CollidingTraffic \
Geomatry/11152ColorfulFlowers \
Geomatry/10927BrightLights \
Geomatry/10263Railway \
DP/787MaximumSub-sequenceProduct \
DP/11450WeddingShopping \
CodeChef/ShackDown/D \
CodeChef/ShackDown/C \
CodeChef/ShackDown/B \
CodeChef/ShackDown/A \
CodeChef/MayCookOff/D \
CodeChef/MayCookOff/C \
CodeChef/MayCookOff/B \
CodeChef/MayCookOff/A \

