INSERT INTO `Languages` (`language`, `languageCode`, `region`, `isDefault`) VALUES
('Afrikaans','af-ZA',NULL,0),
('Bahasa Indonesia','id-ID',NULL,0),
('Bahasa Melayu','ms-MY',NULL,0),
('Català','ca-ES',NULL,0),
('Čeština','cs-CZ',NULL,0),
('Deutsch','de-DE',NULL,0),
('English','en-AU','Australia',0),
('English','en-CA','Canada',0),
('English','en-IN','India',0),
('English','en-NZ','New Zealand',0),
('English','en-ZA','South Africa',0),
('English','en-GB','United Kingdom',0),
('English','en-US','United States',0),
('Español','es-AR','Argentina',0),
('Español','es-BO','Bolivia',0),
('Español','es-CL','Chile',0),
('Español','es-CO','Colombia',0),
('Español','es-CR','Costa Rica',0),
('Español','es-EC','Ecuador',0),
('Español','es-SV','El Salvador',0),
('Español','es-ES','España',0),
('Español','es-US','Estados Unidos',0),
('Español','es-GT','Guatemala',0),
('Español','es-HN','Honduras',0),
('Español','es-MX','México',0),
('Español','es-NI','Nicaragua',0),
('Español','es-PA','Panamá',0),
('Español','es-PY','Paraguay',0),
('Español','es-PE','Perú',0),
('Español','es-PR','Puerto Rico',0),
('Español','es-DO','República Dominicana',0),
('Español','es-UY','Uruguay',0),
('Español','es-VE','Venezuela',0),
('Euskara','eu-ES',NULL,0),
('Français','fr-FR',NULL,0),
('Galego','gl-ES',NULL,0),
('Hrvatski','hr_HR',NULL,0),
('IsiZulu','zu-ZA',NULL,0),
('Íslenska','is-IS',NULL,0),
('Italiano','it-IT','Italia',0),
('Italiano','it-CH','Svizzera',0),
('Magyar','hu-HU',NULL,0),
('Nederlands','nl-NL',NULL,0),
('Norsk bokmål','nb-NO',NULL,0),
('Polski','pl-PL',NULL,0),
('Português','pt-BR','Brasil',0),
('Português','pt-PT','Portugal',0),
('Română','ro-RO',NULL,0),
('Slovenčina','sk-SK',NULL,0),
('Suomi','fi-FI',NULL,0),
('Svenska','sv-SE',NULL,0),
('Türkçe','tr-TR',NULL,0),
('български','bg-BG',NULL,0),
('Pусский','ru-RU',NULL,0),
('Српски','sr-RS',NULL,0),
('한국어','ko-KR',NULL,0),
('中文','cmn-Hans-CN','普通话 (中国大陆)',0),
('中文','cmn-Hans-HK','普通话 (香港)',0),
('中文','cmn-Hant-TW','中文 (台灣)',0),
('中文','yue-Hant-HK','粵語 (香港)',0),
('日本語','ja-JP',NULL,0),
('Lingua latīna','la',NULL,0);

INSERT INTO `Users` (`idUser`, `username`, `password`, `email`, `idLanguage`) VALUES
(1,'blastoy','justatest','blastoy4@gmail.com', 13),
(2,'blastoy4','justanothertest','blastoy44@gmail.com', 13);




